// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            Future<void>  loadSoundFont({required List<int> soundFontData }) => RustLib.instance.api.crateApiMidiPlaybackLoadSoundFont(soundFontData: soundFontData);

Future<void>  loadMidiData({required List<int> midiData }) => RustLib.instance.api.crateApiMidiPlaybackLoadMidiData(midiData: midiData);

Future<void>  startPlayback() => RustLib.instance.api.crateApiMidiPlaybackStartPlayback();

            
            